<?php include __DIR__ . '/header.phtml' ?>

    <h1>Finishing installation</h1>

    <div class="alert alert-warning">
        <strong>
            <span class="fa fa-exclamation-triangle"></span> Please delete the folder <strong>public/install</strong> before using CacoCloud!
        </strong>
    </div>

    <hr />

    <a href="/" class="btn btn-success">
        <span class="fa fa-chevron-right"></span> Proceed
    </a>

<?php include __DIR__ . '/footer.phtml' ?>